server:
  port: 28080
spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/co-dev
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      data-locations: classpath:/sql/user.sql
      mode: never
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 0 # default
      timeout: 60000
      lettuce:
        pool:
          max-active: 8 # default
          max-idle: 8 # default
          min-idle: 2 # custom
          max-wait: -1

jwt:
  secret-key: ${SECRET_KEY}
  access-token-expiration: 1800 # 30분
  refresh-token-expiration: 1296000 # 2주

logging:
  level:
    root: info
    com.zaxxer.hikari.HikariConfig: debug