server:
  port:
spring:
  application:
    name:
  datasource:
    url:
    username:
    password:
  sql:
    init:
      data-locations:
      mode:
  jpa:
    open-in-view:
    hibernate:
      ddl-auto:
    show-sql:
    defer-datasource-initialization:
  data:
    redis:
      host:
      port:
      database:
      timeout:
      lettuce:
        pool:
          max-active:
          max-idle:
          min-idle:
          max-wait:

jwt:
  secret-key:
  access-token-expiration:
  refresh-token-expiration:
  admin-token-expiration:

logging:
  level:
    root:
    com.zaxxer.hikari.HikariConfig: